name = tarot_redo
title = Tarot Redo
description = Extension of the Tarot mod to add in-world Tarot cards
supported_games = *
depends = tarot, flow
optional_depends = default, dye, mcl_core, mcl_books, mcl_dyes, mcl_dye, tt
author = wks
